---
- name: install apache
  apt:
    name: apache2
    state: present
- name: Copy across new virtual host
  template:
    src: vhosts.conf.j2
    dest: /etc/apache2/sites-available/vm.conf
  notify:
    - reload apache
- name: Remove default virtual host
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - reload apache
- name: Enable new vagrant virtual host
  file:
    src: /etc/apache2/sites-available/vm.conf
    dest: /etc/apache2/sites-enabled/vm.conf
    state: link
  notify:
    - reload apache
- name: Remove /var/www folder
  file:
    path: /var/www
    state: absent
  notify:
    - reload apache
- name: Create simlink /vagrant/www /var/www
  file:
    src: /vagrant/www
    dest: /var/www
    state: link
  notify:
    - reload apache
- name: Create/update VM welcome page
  template:
    src: vm_welcome_page.html.j2
    dest: /var/www/vm/public/index.html
  notify:
    - reload apache
